export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Puducherry',
];

export const CATEGORY_ICONS: Record<string, string> = {
  'rainwater-harvesting': 'Droplets',
  'organic-farming': 'Sprout',
  'mixed-farming': 'Wheat',
  'natural-pest-control': 'Bug',
  'herbal-medicine': 'Leaf',
  'waste-management': 'Recycle',
  'renewable-energy': 'Sun',
  'eco-friendly-housing': 'Home',
  'food-preservation': 'Apple',
  'seed-preservation': 'Seedling',
};

export const BADGES = [
  { id: 'first_submission', name: 'First Seed', description: 'Submitted first practice' },
  { id: 'five_practices', name: 'Green Guardian', description: '5 approved practices' },
  { id: 'ten_practices', name: 'Heritage Keeper', description: '10 approved practices' },
  { id: 'state_champion', name: 'State Champion', description: 'Top contributor in a state' },
  { id: 'expert_validated', name: 'Expert Validated', description: 'First practice approved by expert' },
];
